In [2]:
import numpy as np

In [8]:
mat_eye = np.eye(50)
mat_eye

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [28]:
ones_mat = np.ones((50, 50))
ones_mat

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [29]:
mat_eye - 2

array([[-1., -2., -2., ..., -2., -2., -2.],
       [-2., -1., -2., ..., -2., -2., -2.],
       [-2., -2., -1., ..., -2., -2., -2.],
       ...,
       [-2., -2., -2., ..., -1., -2., -2.],
       [-2., -2., -2., ..., -2., -1., -2.],
       [-2., -2., -2., ..., -2., -2., -1.]])

In [15]:
m_1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
m_2 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

m_1 @ m_2

array([[ 50,  60],
       [114, 140]])

In [17]:
m_2 @ m_1

array([[11, 14, 17, 20],
       [23, 30, 37, 44],
       [35, 46, 57, 68],
       [47, 62, 77, 92]])

In [22]:
m_1.shape, m_2.shape

((2, 4), (4, 2))

In [20]:
m_1 * m_2.T

array([[ 1,  6, 15, 28],
       [10, 24, 42, 64]])

In [21]:
m_1, m_1.T

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]]))

In [23]:
arr = np.array([1, 2, 3, 2, 3, 4, 4, 5, 5, 6, 7, 8, 9])

In [24]:
np.bincount(arr)

array([0, 1, 2, 2, 2, 2, 1, 1, 1, 1], dtype=int64)

In [31]:
m_a = m_2 @ m_1
m_a

array([[11, 14, 17, 20],
       [23, 30, 37, 44],
       [35, 46, 57, 68],
       [47, 62, 77, 92]])

In [33]:
eigvals, eigvecs = np.linalg.eig(m_a)
eigvals

array([ 1.89154129e+02+0.00000000e+00j,  8.45871041e-01+0.00000000e+00j,
       -1.88577119e-15+1.86090707e-15j, -1.88577119e-15-1.86090707e-15j])

In [37]:
mat_a = np.ones((10000, 10000)) * 5

In [ ]:
np.linalg.svd(mat_a + np.eye(10000))